### ISSUE TITLE
data-handler.js

### ISSUE THREAD

**Issue by Karyum** [WebAhead12/ExpressList#10]
1) I would argue this is a badly named function 😆  https://github.com/WebAhead12/ExpressList/blob/main/data-handler.js#L16-L18
2) [you don't need this](https://github.com/WebAhead12/ExpressList/blob/main/data-handler.js#L12-L14)
3) [why do you hate empty lines between lines of code 😄  ](https://github.com/WebAhead12/ExpressList/blob/main/data-handler.js#L39-L105)

> I will return to this, I need to code review other teams lol

**Comment by Diabolicah** [comment]
1)Done.
2)Done.
3)Done.
In commit
96dbecf49604cfc6b2485409077d2c23163ad0b7
