### ISSUE TITLE
Small notes on server.js

### ISSUE THREAD

**Issue by Karyum** [WebAhead12/ExpressList#8]
@Diabolicah truly think about this before arguing!

I might do this review by file, since the project is kinda big 😅 

1) [not needed require (probably by mistake from vscode)](https://github.com/WebAhead12/ExpressList/blob/main/server.js#L5)
2) change `    if (user != undefined) req.user = user;` to     `if (user) req.user = user;`
3) https://github.com/WebAhead12/ExpressList/blob/main/server.js#L26-L28 you have `req.user` do you really need this ? 
4) https://github.com/WebAhead12/ExpressList/blob/main/server.js#L39-L41 This is not really clear, you make the auth token and then check the password ? should be the other way around
5) [I mean there is this again](https://github.com/WebAhead12/ExpressList/blob/main/server.js#L50) you have the `req.user`, you don't need to refetch the data. you don't need `checkUserLoginData`
6) [This is kinda unreadable](https://github.com/WebAhead12/ExpressList/blob/main/server.js#L125-L143) I need spaces new lines and comments here

**Comment by Diabolicah** [comment]
1) done.
2) done.
3) done.
4) done.
5) This checks if the user specified in the parms exists, so that you can search for other users to dolist, and not just your own.
6) done.
In
583c1823a099a266ab0fa5b2f2f145dcab3f9da1
